# Generated by Django 2.2.6 on 2019-10-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=15)),
                ('port', models.CharField(max_length=5)),
                ('user', models.CharField(max_length=10)),
                ('password', models.CharField(blank=True, max_length=14, null=True)),
                ('group', models.PositiveIntegerField(blank=True, choices=[(1, 'master'), (2, 'worker'), (3, 'etcd'), (4, 'certs'), (5, 'keepalived'), (6, 'k8s-harbor')], null=True)),
            ],
        ),
    ]
